# syntax=docker/dockerfile:1

# Use bellsoft/liberica as base image
FROM bellsoft/liberica-openjdk-alpine:17 AS base

ENV WORK_DIR=/opt/app

# Set the working directory
WORKDIR ${WORK_DIR}

# Set a non-root user for security
RUN addgroup -S spring && adduser -S spring -G spring

# Switch to the non-root user
USER spring:spring

# Copy the application JAR
COPY spring-boot-app/target/spring-boot-web.jar app.jar

# Expose application port
EXPOSE 8084

ENTRYPOINT ["java","-jar","app.jar"]